
name: Deploy Infra

on:
  push:
    branches: 
      - main

permissions:
  id-token: write
  contents: write

jobs:
  backend:
    runs-on: ubuntu-latest
    environment: main
    steps:
      - uses: actions/checkout@v3
      - uses: hashicorp/setup-terraform@v2.0.3

      - name: Terraform fmt
        id: fmt
        run: terraform fmt -check
        working-directory: ./backend

      - name: Terraform Init
        id: init
        run: terraform init 
        working-directory: ./backend
        env:
          ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
          ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}

      - name: Terraform Validate
        id: validate
        run: terraform validate -no-color
        working-directory: ./backend

      - uses: azure/login@v1.4.7
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Terraform Plan
        id: plan
        run: terraform plan -no-color 
        working-directory: ./backend

      - name: Terraform Apply
        id: apply
        run: terraform apply -auto-approve -input=false -no-color
        working-directory: ./backend

      - name: Azure CLI script
        if: ${{ always() }}
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az logout
            az cache purge
            az account clear
